/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Booking {
  'id' : bigint,
  'weight' : string,
  'customerName' : string,
  'status' : Status,
  'goodsType' : string,
  'userId' : [] | [Principal],
  'trackingId' : string,
  'submittedAt' : bigint,
  'deliveryLocation' : string,
  'preferredDate' : string,
  'phone' : string,
  'pickupLocation' : string,
}
export interface ContactMessage {
  'id' : bigint,
  'name' : string,
  'submittedAt' : bigint,
  'email' : string,
  'message' : string,
  'phone' : string,
}
export type Status = { 'cancelled' : null } |
  { 'pending' : null } |
  { 'inTransit' : null } |
  { 'delivered' : null } |
  { 'confirmed' : null };
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'getAllBookings' : ActorMethod<[], Array<Booking>>,
  'getAllContactMessages' : ActorMethod<[], Array<ContactMessage>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getMyBookings' : ActorMethod<[], Array<Booking>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'submitBooking' : ActorMethod<
    [string, string, string, string, string, string, string],
    string
  >,
  'submitBookingAsUser' : ActorMethod<
    [string, string, string, string, string, string, string],
    string
  >,
  'submitContactMessage' : ActorMethod<
    [string, string, string, string],
    string
  >,
  'trackShipment' : ActorMethod<
    [string],
    [] | [
      {
        'customerName' : string,
        'status' : string,
        'trackingId' : string,
        'deliveryLocation' : string,
        'preferredDate' : string,
        'pickupLocation' : string,
      }
    ]
  >,
  'updateBookingStatus' : ActorMethod<[bigint, string], string>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];